### PR TITLE
New preprocessor sigil (without interpunctuation)

### PR DESCRIPTION
**Pull request by marcioAlmada**
After #29  and not much consent, I decided to make this experiment so we could get rid of the interpuctuation. The middle dot has been causing pain for most people. Please refer to tests, try the split view to see how the DSL changed.

### CODE REVIEW

**Comment by marcioAlmada** [comment]
@chris-kruining what was the reason Jquery did this? We could do it for a very good reason, maybe.

**Comment by chris-kruining** [comment]
I've just taken a look at the enum implementation, Am I right that the reason that you return anonymous class instances in the store in because you can call instance of on the enum value? because as far as I understand I could call `Fruits::Apple::Apple::Apple::Apple::Apple::Apple::Apple::Apple` an infinite amount of times. maybe you might want to limit that in a way.

No offence, just trying to be helpful :wink:

**Comment by marcioAlmada** [comment]
@chris-kruining lol, gotcha, I'm going to fix it.

**Comment by assertchris** [comment]
This looks interesting, and I think it reduces the cognitive overload of too many middle dots.

**Pull request merged**
